# Generated by Django 6.0 on 2026-07-08 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=20)),
                ('tags', models.CharField(help_text='Comma-separated list of tags', max_length=200)),
                ('related_topics', models.CharField(help_text='Comma-separated list of related topic IDs', max_length=200)),
                ('cover_url', models.URLField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=30)),
                ('item_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('platform', models.CharField(choices=[('Frontend Mentor', 'Frontend Mentor'), ('LeetCode', 'LeetCode'), ('GitHub', 'GitHub'), ('HackerRank', 'HackerRank'), ('Project Euler', 'Project Euler'), ('Personal Project', 'Personal Project')], max_length=50)),
                ('link', models.URLField(blank=True)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=20)),
                ('tags', models.CharField(help_text='Comma-separated list of tags', max_length=200)),
                ('status', models.CharField(choices=[('Solved', 'Solved'), ('Attempted', 'Attempted'), ('To Do', 'To Do')], max_length=20)),
                ('my_code', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('mistakes', models.TextField(blank=True)),
                ('better_solution', models.TextField(blank=True)),
                ('editorial_link', models.URLField(blank=True)),
                ('video_link', models.URLField(blank=True)),
                ('time_complexity', models.CharField(blank=True, max_length=50)),
                ('space_complexity', models.CharField(blank=True, max_length=50)),
                ('date_solved', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='core.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Mistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=150)),
                ('mistake', models.CharField(max_length=200)),
                ('wrong_approach', models.TextField(blank=True)),
                ('correct_approach', models.TextField(blank=True)),
                ('lesson_learned', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_mistakes', to='core.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=150)),
                ('next_revision_date', models.DateField()),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='core.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('code', models.TextField()),
                ('language', models.CharField(choices=[('python', 'Python'), ('django', 'Django'), ('html', 'HTML'), ('css', 'CSS'), ('javascript', 'JavaScript')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(help_text='Comma-separated list of tags', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('code', models.TextField()),
                ('explanation', models.TextField()),
                ('complexity_time', models.CharField(blank=True, max_length=50)),
                ('complexity_space', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='core.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('code_block', models.TextField(blank=True)),
                ('formula_section', models.TextField(blank=True)),
                ('important_tips', models.TextField(blank=True)),
                ('references', models.TextField(blank=True, help_text='Newline-separated list of reference links or texts')),
                ('tags', models.CharField(help_text='Comma-separated list of tags', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('youtube_url', models.URLField()),
                ('youtube_id', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('timestamps', models.TextField(blank=True, help_text='Format: MM:SS - Label, one per line')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
